---
title: "Лабораторна робота №2. Ухвалення рішень в умовах невизначеності. Частина 2"
description: "Моніторинг та керування в слабкоструктурованих процесах і системах | КрНУ ім. М. Остроградського"
author: "Ярослав Фігас, 2026"
date: today
lang: uk
jupyter: python3

format:
  html:
    toc: true
    toc-location: right
    number-sections: false
    code-fold: true
    embed-resources: true
    self-contained-math: true
---

# Мета роботи
Опанувати похідні критерії прийняття рішень і навчитися застосовувати їх у задачах вибору в умовах невизначеності та ризику: *Гурвіца*, *Ходжа–Лемана*, *Гермейєра* і *критерій добутків*.

# Індивідуальне завдання

## Умови завдання

Було наведено заготовку для індивідуального варіанта.

Рекомендується використати *власну постановку*, але зберегти логіку другої частини роботи:

1. задати матрицю виграшів;
2. задати ймовірності станів;
3. вибрати параметри $\alpha$ і $v$;
4. обчислити всі критерії;
5. інтерпретувати, як змінюється рішення залежно від характеру невизначеності.

## Виконання роботи

### Підготовка середовища

Для початку потрібно імпортувати потрібні бібліотеки, які необхідні для роботи. Numpy - для обчислень, а pandas - для роботи з данними.

In [106]:
import numpy as np
import pandas as pd

Далі використаємо таку саму матрицю виграшів, що і в попередній лабораторній роботі.

In [107]:
student_alternatives = [
    "Моніторинг ситуації",
    "Обмеження доступу",
    "Резервна інфраструктура",
    "Блокування інфраструктури"
]

student_states = [
    "Відсутність загрози",
    "Низька загроза",
    "Середня загроза",
    "Велика загроза"
]

student_matrix = np.array([
    [10,  4, -2, -10],
    [ 6,  7,  1, -5],
    [ 1,  3,  7,  2],
    [ -7, -4 , 3, 10]
], dtype=float)

student_probabilities = np.array([0.40, 0.30, 0.25, 0.05], dtype=float)

student_df = pd.DataFrame(student_matrix, index=student_alternatives, columns=student_states)
student_df

,Відсутність загрози,Низька загроза,Середня загроза,Велика загроза
Моніторинг ситуації,10.0,4.0,-2.0,-10.0
Обмеження доступу,6.0,7.0,1.0,-5.0
Резервна інфраструктура,1.0,3.0,7.0,2.0
Блокування інфраструктури,-7.0,-4.0,3.0,10.0

### Критерій Гурвіца

Далі перейдемо до перевірки критеріїв. Почнімо перевірку з критерію Гурвіца. Даний критерій використовує показник песимізму $alpfa$, де чим більше значення, ти більш песимістичним розрахунок буде. Для роботи використаємо проміжок від 0 до 1 з кроком 0.2. З результатів можна помітити що чим більше даний показник, тим сильніше альтернатива хилиться у бік резервної інфраструктури.

In [108]:
def hurwicz_criterion(matrix, alternatives, alpha=0.5):
    row_mins = matrix.min(axis=1)
    row_maxs = matrix.max(axis=1)
    scores = alpha * row_mins + (1 - alpha) * row_maxs
    best_index = scores.argmax()

    result_df = pd.DataFrame({
        "Альтернатива": alternatives,
        "min по рядку": row_mins,
        "max по рядку": row_maxs,
        "Оцінка Гурвіца": scores
    })
    return result_df, alternatives[best_index], scores[best_index]
    
for alpha in np.arange(0, 1.1, 0.2):
    hurwicz_df, hurwicz_best_alt, hurwicz_best_value = hurwicz_criterion(
        student_matrix,
        student_alternatives,
        alpha=alpha
    )

    display(hurwicz_df)
    print(f"Параметр alpha = {alpha}")
    print(f"Оптимальна альтернатива за критерієм Гурвіца: {hurwicz_best_alt}")
    print(f"Оцінка критерію: {hurwicz_best_value:.3f}")

                Альтернатива  min по рядку  max по рядку  Оцінка Гурвіца
0        Моніторинг ситуації         -10.0          10.0            10.0
1          Обмеження доступу          -5.0           7.0             7.0
2    Резервна інфраструктура           1.0           7.0             7.0
3  Блокування інфраструктури          -7.0          10.0            10.0

Параметр alpha = 0.0
Оптимальна альтернатива за критерієм Гурвіца: Моніторинг ситуації
Оцінка критерію: 10.000

                Альтернатива  min по рядку  max по рядку  Оцінка Гурвіца
0        Моніторинг ситуації         -10.0          10.0             6.0
1          Обмеження доступу          -5.0           7.0             4.6
2    Резервна інфраструктура           1.0           7.0             5.8
3  Блокування інфраструктури          -7.0          10.0             6.6

Параметр alpha = 0.2
Оптимальна альтернатива за критерієм Гурвіца: Блокування інфраструктури
Оцінка критерію: 6.600

                Альтернатива  min по рядку  max по рядку  Оцінка Гурвіца
0        Моніторинг ситуації         -10.0          10.0             2.0
1          Обмеження доступу          -5.0           7.0             2.2
2    Резервна інфраструктура           1.0           7.0             4.6
3  Блокування інфраструктури          -7.0          10.0             3.2

Параметр alpha = 0.4
Оптимальна альтернатива за критерієм Гурвіца: Резервна інфраструктура
Оцінка критерію: 4.600

                Альтернатива  min по рядку  max по рядку  Оцінка Гурвіца
0        Моніторинг ситуації         -10.0          10.0            -2.0
1          Обмеження доступу          -5.0           7.0            -0.2
2    Резервна інфраструктура           1.0           7.0             3.4
3  Блокування інфраструктури          -7.0          10.0            -0.2

Параметр alpha = 0.6000000000000001
Оптимальна альтернатива за критерієм Гурвіца: Резервна інфраструктура
Оцінка критерію: 3.400

                Альтернатива  min по рядку  max по рядку  Оцінка Гурвіца
0        Моніторинг ситуації         -10.0          10.0            -6.0
1          Обмеження доступу          -5.0           7.0            -2.6
2    Резервна інфраструктура           1.0           7.0             2.2
3  Блокування інфраструктури          -7.0          10.0            -3.6

Параметр alpha = 0.8
Оптимальна альтернатива за критерієм Гурвіца: Резервна інфраструктура
Оцінка критерію: 2.200

                Альтернатива  min по рядку  max по рядку  Оцінка Гурвіца
0        Моніторинг ситуації         -10.0          10.0           -10.0
1          Обмеження доступу          -5.0           7.0            -5.0
2    Резервна інфраструктура           1.0           7.0             1.0
3  Блокування інфраструктури          -7.0          10.0            -7.0

Параметр alpha = 1.0
Оптимальна альтернатива за критерієм Гурвіца: Резервна інфраструктура
Оцінка критерію: 1.000

### Критерій Ходжа-Лемана

Наступним критерієм для перевірки буде критерій Ходжа–Лемана, який дозволяє поєднати довіру до ймовірностей і обережність щодо найгіршого сценарію. Для цього потребується додаткова величина $v$, яка означає довіра розподілу. Для завдання також візьмемо значення від 0 до 1 з кроком 0.2. У результаті перевірки критерію вияснилось, що поки довіра не є максимальною, використовується резервна інфраструктура, а при максимальній довіри використовується обмеження доступу.

In [109]:
def hodge_lehmann_criterion(matrix, alternatives, probs, v=0.5):
    row_mins = matrix.min(axis=1)
    expected_values = matrix @ probs
    scores = v * expected_values + (1 - v) * row_mins
    best_index = scores.argmax()

    result_df = pd.DataFrame({
        "Альтернатива": alternatives,
        "min по рядку": row_mins,
        "Математичне сподівання": expected_values,
        "Оцінка Ходжа–Лемана": scores
    })
    return result_df, alternatives[best_index], scores[best_index]
    
for v in np.arange(0, 1.1, 0.2):
    hl_df, hl_best_alt, hl_best_value = hodge_lehmann_criterion(
        student_matrix,
        student_alternatives,
        student_probabilities,
        v=v
    )

    display(hl_df)
    print(f"Параметр v = {v}")
    print(f"Оптимальна альтернатива за критерієм Ходжа–Лемана: {hl_best_alt}")
    print(f"Оцінка критерію: {hl_best_value:.3f}")

,Альтернатива,min по рядку,Математичне сподівання,Оцінка Ходжа–Лемана
0,Моніторинг ситуації,-10.0,4.20,-10.0
1,Обмеження доступу,-5.0,4.50,-5.0
2,Резервна інфраструктура,1.0,3.15,1.0
3,Блокування інфраструктури,-7.0,-2.75,-7.0

Параметр v = 0.0
Оптимальна альтернатива за критерієм Ходжа–Лемана: Резервна інфраструктура
Оцінка критерію: 1.000

,Альтернатива,min по рядку,Математичне сподівання,Оцінка Ходжа–Лемана
0,Моніторинг ситуації,-10.0,4.20,-7.16
1,Обмеження доступу,-5.0,4.50,-3.10
2,Резервна інфраструктура,1.0,3.15,1.43
3,Блокування інфраструктури,-7.0,-2.75,-6.15

Параметр v = 0.2
Оптимальна альтернатива за критерієм Ходжа–Лемана: Резервна інфраструктура
Оцінка критерію: 1.430

,Альтернатива,min по рядку,Математичне сподівання,Оцінка Ходжа–Лемана
0,Моніторинг ситуації,-10.0,4.20,-4.32
1,Обмеження доступу,-5.0,4.50,-1.20
2,Резервна інфраструктура,1.0,3.15,1.86
3,Блокування інфраструктури,-7.0,-2.75,-5.30

Параметр v = 0.4
Оптимальна альтернатива за критерієм Ходжа–Лемана: Резервна інфраструктура
Оцінка критерію: 1.860

,Альтернатива,min по рядку,Математичне сподівання,Оцінка Ходжа–Лемана
0,Моніторинг ситуації,-10.0,4.20,-1.48
1,Обмеження доступу,-5.0,4.50,0.70
2,Резервна інфраструктура,1.0,3.15,2.29
3,Блокування інфраструктури,-7.0,-2.75,-4.45

Параметр v = 0.6000000000000001
Оптимальна альтернатива за критерієм Ходжа–Лемана: Резервна інфраструктура
Оцінка критерію: 2.290

,Альтернатива,min по рядку,Математичне сподівання,Оцінка Ходжа–Лемана
0,Моніторинг ситуації,-10.0,4.20,1.36
1,Обмеження доступу,-5.0,4.50,2.60
2,Резервна інфраструктура,1.0,3.15,2.72
3,Блокування інфраструктури,-7.0,-2.75,-3.60

Параметр v = 0.8
Оптимальна альтернатива за критерієм Ходжа–Лемана: Резервна інфраструктура
Оцінка критерію: 2.720

,Альтернатива,min по рядку,Математичне сподівання,Оцінка Ходжа–Лемана
0,Моніторинг ситуації,-10.0,4.20,4.20
1,Обмеження доступу,-5.0,4.50,4.50
2,Резервна інфраструктура,1.0,3.15,3.15
3,Блокування інфраструктури,-7.0,-2.75,-2.75

Параметр v = 1.0
Оптимальна альтернатива за критерієм Ходжа–Лемана: Обмеження доступу
Оцінка критерію: 4.500

### Критерій Гермейєра

Наступним критерієм для аналізу буде критерій Гермейєра, який застосовується у матриці збитків, тобто матриці мають бути повністю від'ємні. Оптимальним варіантом виявився обмеження доступу, оскільки при його використанні збитків буде найменше.

In [110]:
def hermeyer_criterion(matrix, alternatives, probs):
    if np.any(matrix > 0):
        shift = matrix.max() + 1
        transformed_matrix = matrix - shift
    else:
        transformed_matrix = matrix.copy()

    weighted = transformed_matrix * probs
    row_mins = weighted.min(axis=1)
    best_index = row_mins.argmax()

    transformed_df = pd.DataFrame(transformed_matrix, index=alternatives, columns=student_states)
    weighted_df = pd.DataFrame(weighted, index=alternatives, columns=student_states)
    summary_df = pd.DataFrame({
        "Альтернатива": alternatives,
        "min(p_j * e_ij)": row_mins
    })
    return transformed_df, weighted_df, summary_df, alternatives[best_index], row_mins[best_index]

hermeyer_transformed_df, hermeyer_weighted_df, hermeyer_summary_df, hermeyer_best_alt, hermeyer_best_value = hermeyer_criterion(
    student_matrix,
    student_alternatives,
    student_probabilities
)

print("Перетворена матриця для критерію Гермейєра:")
display(hermeyer_transformed_df)

print("Зважені значення p_j * e_ij:")
display(hermeyer_weighted_df)

print("Підсумкова таблиця:")
display(hermeyer_summary_df)

print(f"Оптимальна альтернатива за критерієм Гермейєра: {hermeyer_best_alt}")
print(f"Оцінка критерію: {hermeyer_best_value:.3f}")

Перетворена матриця для критерію Гермейєра:

,Відсутність загрози,Низька загроза,Середня загроза,Велика загроза
Моніторинг ситуації,-1.0,-7.0,-13.0,-21.0
Обмеження доступу,-5.0,-4.0,-10.0,-16.0
Резервна інфраструктура,-10.0,-8.0,-4.0,-9.0
Блокування інфраструктури,-18.0,-15.0,-8.0,-1.0

Зважені значення p_j * e_ij:

,Відсутність загрози,Низька загроза,Середня загроза,Велика загроза
Моніторинг ситуації,-0.4,-2.1,-3.25,-1.05
Обмеження доступу,-2.0,-1.2,-2.50,-0.80
Резервна інфраструктура,-4.0,-2.4,-1.00,-0.45
Блокування інфраструктури,-7.2,-4.5,-2.00,-0.05

Підсумкова таблиця:

                Альтернатива  min(p_j * e_ij)
0        Моніторинг ситуації            -3.25
1          Обмеження доступу            -2.50
2    Резервна інфраструктура            -4.00
3  Блокування інфраструктури            -7.20

Оптимальна альтернатива за критерієм Гермейєра: Обмеження доступу
Оцінка критерію: -2.500

### Критерій добутку

Достанній критерій який буде використаний це критерій добутку. Для його використання спочатку треба змінити таблицю у додатній вигляд. Провевши розрахунки, виявилось що резервна інфраструктура буде найоптимальнішим варіантом.

In [111]:
def product_criterion(matrix, alternatives):
    # Для критерію добутків потрібні додатні значення.
    if np.any(matrix <= 0):
        shift = abs(matrix.min()) + 1
        transformed_matrix = matrix + shift
    else:
        transformed_matrix = matrix.copy()

    row_products = transformed_matrix.prod(axis=1)
    best_index = row_products.argmax()

    transformed_df = pd.DataFrame(transformed_matrix, index=alternatives, columns=student_states)
    summary_df = pd.DataFrame({
        "Альтернатива": alternatives,
        "Добуток елементів рядка": row_products
    })
    return transformed_df, summary_df, alternatives[best_index], row_products[best_index]

product_transformed_df, product_summary_df, product_best_alt, product_best_value = product_criterion(
    student_matrix,
    student_alternatives
)

print("Перетворена матриця для критерію добутків:")
display(product_transformed_df)

print("Підсумкова таблиця:")
display(product_summary_df)

print(f"Оптимальна альтернатива за критерієм добутків: {product_best_alt}")
print(f"Оцінка критерію: {product_best_value:.3f}")

Перетворена матриця для критерію добутків:

,Відсутність загрози,Низька загроза,Середня загроза,Велика загроза
Моніторинг ситуації,21.0,15.0,9.0,1.0
Обмеження доступу,17.0,18.0,12.0,6.0
Резервна інфраструктура,12.0,14.0,18.0,13.0
Блокування інфраструктури,4.0,7.0,14.0,21.0

Підсумкова таблиця:

                Альтернатива  Добуток елементів рядка
0        Моніторинг ситуації                   2835.0
1          Обмеження доступу                  22032.0
2    Резервна інфраструктура                  39312.0
3  Блокування інфраструктури                   8232.0

Оптимальна альтернатива за критерієм добутків: Резервна інфраструктура
Оцінка критерію: 39312.000

### Математичне сподівання і ризик результату

На останок буде перевірено значення очікуваного виграшу, дисперсію та середньоквадратичне відхилення в усіх альтернативах.
Серед результатів можна помітити що найстабільнішим є варіант резервної інфраструктури, оскільки дисперсія найменша.

In [112]:
def expected_value_and_risk(matrix, alternatives, probs):
    expected_values = matrix @ probs
    variances = ((matrix - expected_values.reshape(-1, 1)) ** 2 @ probs)
    stds = np.sqrt(variances)

    result_df = pd.DataFrame({
        "Альтернатива": alternatives,
        "Математичне сподівання": expected_values,
        "Дисперсія": variances,
        "Середньоквадратичне відхилення": stds
    })
    return result_df
risk_df = expected_value_and_risk(student_matrix, student_alternatives, student_probabilities)
risk_df

,Альтернатива,Математичне сподівання,Дисперсія,Середньоквадратичне відхилення
0,Моніторинг ситуації,4.20,33.1600,5.758472
1,Обмеження доступу,4.50,10.3500,3.217142
2,Резервна інфраструктура,3.15,5.6275,2.372235
3,Блокування інфраструктури,-2.75,24.0875,4.907902

### Підсумкове порівняння критеріїв

Для зручності всі результати зведемо до однієї таблиці.

In [113]:
summary_df = pd.DataFrame({
    "Критерій": ["Гурвіца", "Ходжа–Лемана", "Гермейєра", "Добутків"],
    "Оптимальна альтернатива": [
        hurwicz_best_alt,
        hl_best_alt,
        hermeyer_best_alt,
        product_best_alt
    ],
    "Оцінка": [
        round(hurwicz_best_value, 3),
        round(hl_best_value, 3),
        round(hermeyer_best_value, 3),
        round(product_best_value, 3)
    ]
})

summary_df

       Критерій  Оптимальна альтернатива   Оцінка
0       Гурвіца  Резервна інфраструктура      1.0
1  Ходжа–Лемана        Обмеження доступу      4.5
2     Гермейєра        Обмеження доступу     -2.5
3      Добутків  Резервна інфраструктура  39312.0

# Висновки

У цій лабораторній роботі було проведено аналіз матриці виграшів на тему "Стратегія реагування на інцедент" розміром 4 на 4. Для кожного зі станів у даній матриці було додано свою ймовірність, де на кращу подію ймовірність найвища і спадала сильніще в залежності від критичності ситуації.
Порівнюючи отримані в цій лабораторній роботі результати з результатами попередньої роботи, можна знайти певну параллель. В критерії Гурвіца можна помітити результати як критерію оптимізму, як і критерію Вальда. Тобто показник $\alpha$ вказує на те, наскільки песимістично чи оптимістично особа дивиться на ситуацію, що вприлає на стратегію вибору. Також не варто уникати критерій Ходжа–Лемана, який також має результати з критерія Вальда та Байєса-Лапласа. Показник $v$ вказує на рівень довіри до ймовірностей. В критерії Гермейєра найоптимальнішим варіантом виявилось обмеження обмеження оступу, а критерії добутку - резервна інфраструктура.
Було спостережено що серед усіх критеріїв, в даній ситуації, варіант з резервною інфраструктурою зустрічався найчастіше, після нього обмеження доступу.
Що до використання переглянутих критеріїв, то критерій Гурвіца дозволяє переглянути ситуацію не тільки як оптиміст або песиміст, але і десь посередині; критерій Ходжа-Лемана дозволяє переглянути наскільки збільшиться чи зменшиться прибуток якщо додати до роботи математичне сподівання; критерій Гермейера дозволяє перевірити наскільки високою буде втрата при виборі певного варіанту, що дасть певні знання що до втрат.

# Контрольні питання

 Який зміст має параметр $\alpha$ у критерії *Гурвіца*?

 Параметр $\alpha$ вказує на рівень песемизму, при якому чим ближче до одиниці, тим сильніше критерій Гурвіца схиляється до найменших втрат, тобто до логіки Вальда, в противному випадку -- до логіки максімакс.

У чому полягає зміст параметра $v$ у критерії *Ходжа–Лемана*?

Параметр $v$ вказує на ступінь довіри до розподілу ймовірностей, де чим ближче параметр до одиниці, тим більше Критерій схожий на на критерій Байєса-Лапласа, в інакшому випадку до критерію Вальда.

За яких умов застосовують критерій *Гермейєра*?

Чому для критерію добутків потрібні *додатні* значення?

Тому що при множені на негативне число чи нуль результат може виявитись недостовірним. Наприклад при множені двох поганих значень вийде неймовірно позитивний результат, що є малоймовірним. Або якщо одним зі значеннь буде нуль то попри старання результат вийде ніяким, що теж малоймовірно.

Чим відрізняється аналіз *очікуваного виграшу* від аналізу *ризику*?

Аналіз очікуваного виграшу орієнтується на кількість прибутку чи виграшу в певній ситуації, тоді як аналіз ризику орієнтується на кількість втрат в певній ситуації. Враховуючи це то і вибір критерію для того чи іншого аналізу буде вирізнятись

Чому високе математичне сподівання не завжди означає найкраще рішення?

Тому що в математичному сподіванні є ризик того що можна багато втратити навіть з мінімальною ймовірністю. Воно показує середній виграш чи програш при багаторазовому використанні математичного сподівання.

Як змінюється вибір альтернативи при зростанні песимізму ОПР?

При зростанні песимізму ОПР вибір альтернативи змінюється у бік зменшення втрат, ніж до збільшення прибутку.